### PR TITLE
Provide a reasonable mental model for an instruction

### PR DESCRIPTION
**Pull request by zspencer**
Ugh, this took a while to write. Basically I want to ensure that:
1. Students kind of see most of computer programming is storing and retrieving data and executing functions.
2. I need to figure out how to work function context into this. I am not sure I like the "with" and "on" distinction as I've written it...

### CODE REVIEW

**Comment by zspencer** [comment]
@openspectrum mind giving this a gander?

**Comment by tannerwelsh** [comment]
The examples are useful, but I'm not sure this meets the core criteria of providing an understanding of _what_ an instruction actually is. Why not contextualize instructions within a hierarchy of programs > statements/expressions > instructions > machine code?

Also, the omission of control flow statements leaves a fairly large hole in the mental model. I imagine a student who digs just below the surface will wonder where keywords fit into this model.

**Comment by zspencer** [comment]
I'm pretty unhappy with this in it's entirety, so I'm tempted to just kill it.

Thoughts?

**Comment by jfarmer** [comment]
I agree.  This feels like something done for the sake of "completeness" rather than a specific student need/confusion.  Let's get rid of it,

**Comment by jfarmer** [comment]
Uh, also: merry Christmas! 😃🎄🎅🎅🎅

**Pull request closed without merging**
