### PR TITLE
Add an entry to explain events

### PR DESCRIPTION
**Pull request by tannerwelsh**
Specifically, event listeners in the browser.

If we're looking to provide more general entries, then this could be expanded or split so that it discusses evented programming in general, maybe with examples of event listeners in the browser.

### CODE REVIEW

**Comment by tannerwelsh** [comment]
@zspencer your thoughts would be much appreciated.

**Comment by zspencer** [comment]
My take is that working with DOM events is probably better as a guide than a definition. It's possible to write a very small, syncronous event library in irb:

```
$subscriptions = []
def publish(event)
  $subscriptions.each do |subscription|
    subscription[:callback].call(event)
  end
  true
end

def subscribe(event_name, &callback)
  $subscriptions.push({ :event => event_name, :callback => callback})
  true
end

publish({:name => :hi_five })
# Huh, doesn't do much

subscribe(:hi_five) { puts "SWEET HI FIVE!" }

publish({:name => :hi_five })
# => "Sweet Hi Five!

subscribe(:hi_five) do |event|
  puts "hi five received #{event}"
end 

publish({:name => :hi_five, :other_data => :is_fun})
```

**Comment by zspencer** [comment]
If you can grok events at the "publish/subscribe" level, moving to asyncronous/user-caused/api-caused events becomes much easier to get (IMO)

**Comment by tannerwelsh** [comment]
Thanks @zspencer . Just pushed some updates.

If you like, I'll go ahead and merge.

**Comment by zspencer** [comment]
:+1:, though I generally include javascript example as well.

I intend to write some css/js that lets people toggle between the language examples are in soon.

**Comment by zspencer** [comment]
I've added a JS example and did a tiny bit of wordsmithing:
- Removing "simple" 
- Putting everything on 80 lines
- Renamed from 'event_name' to 'event_type'

**Comment by tannerwelsh** [comment]
Thanks @zspencer ! Like the improvements.

**Pull request merged**
